### ISSUE TITLE
Consider changing from fog to aws-sdk?

### ISSUE THREAD

**Issue by dblessing** [promisedlandt/cookbook-amazon_dns#3]
Currently fog doesn't appear to support creating a private Route 53 zone. This is essential for us. If I can implement `amazon_dns_zone` and `amazon_dns_record` with the aws-sdk in a backward compatible manner would you consider that pull request? I'd like to try getting those changes into this cookbook before forking and creating my own.

Thanks for your consideration.

**Comment by promisedlandt** [comment]
Absolutely - I probably should have used aws-sdk over fog in the first place.

After the switch, the easiest way to configure is probably to add a `private_zone` attribute to the zone LWRP, defaulting to false.

Looks like we don't even need to consider that flag in the record LWRP.

**Comment by dblessing** [comment]
Great. I'll hack on it sometime soon.

I can confirm that records don't care. I manually created a private zone and then used record to add just fine.

**Comment by promisedlandt** [comment]
Drew, I'm closing this for the time being. If you find the time to work on this, great, I'll happily reopen it.
